### ISSUE TITLE
Offchain Module in Java Sdk 

### ISSUE THREAD

**Issue by judeebene** [diem/client-sdk-java#64]
I noticed there is a new offchain module in the python sdk,  are we expecting the same in Java ?   i will be happy to contribute to it if there is an ongoing effort toward it.

**Comment by xli** [comment]
We'd like to replicate same offchain module in python sdk to Java, but no one works on it yet.
If you'd like to work on it, feel free to start a PR and ping me for any questions.

**Comment by xli** [comment]
will check the offchain module by #71, let me know if you still want to take it.
