### ISSUE TITLE
value = value * this.value… Obfuscation?

### ISSUE THREAD

**Issue by ViralTaco** [diem/client-sdk-java#66]
Hi,
This bugs me:
https://github.com/diem/client-sdk-java/blob/44140a6fddd6cf37a622a4450386a77a9d171167/src/main/java/com/diem/types/Ed25519PublicKey.java#L55
Sure, it's a value. I'm kinda expecting that from a variable. What kind of value? hashCode? Bytes? What does it represent? 
I don't mean to be condescending. It's just confusing. I open the code, this is the first class I look at and I'm greeted with this.
I'd like to propose `key`, `pkey`, `pKey`, `publicKey`, or simply not to use `value` in the `hashCode` method because I have no clue what it does and if I'm confused by it I don't care if it's valid. it's poorly documented at best, wrong, and/or lazy.

**Comment by xli** [comment]
Because this is generated code. The generator generated many classes, it does not know what is value means, hence you may find many classes have value field, however the class name tells what it is, name the "value" field same with class name is redundant.

**Comment by xli** [comment]
checkout https://github.com/diem/diem/tree/master/language/transaction-builder/generator, you are welcome to submit PR to improve it.

**Comment by ViralTaco** [comment]
I see. Would still be nice if you could document generated code. I'll try and take a look this week end if I don't get busy or forget.
